[package]
name = "engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
default-run = "tcheran"

[features]
spsa = []
datagen = ["dep:rand"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "tcheran"
path = "src/main.rs"

[dependencies]
rand = { version = "0.10.0", optional = true }

[build-dependencies]
cc = "1.2.2"

[lints]
workspace = true
