[package]
name = "trainer"
version = "0.0.0"
rust-version = { workspace = true }
edition = { workspace = true }

# Don't add bullet_lib on macOS, as it's guaranteed not to have CUDA
[target.'cfg(not(target_os = "macos"))'.dependencies]
bullet_lib = { git = "https://github.com/jw1912/bullet" }

[dependencies]
viriformat = "2.0.1"
