name: Release

on:
  workflow_dispatch:
  push:
    tags: "v*"

jobs:

  metadata:
    runs-on: ubuntu-latest

    outputs:
      engine-version: ${{ steps.determine-engine-version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - id: determine-engine-version
        name: Determine Engine version
        run: |
          version="${GITHUB_REF##*/}"
          echo "Engine version: $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"

  build-release-binary:
    needs: [metadata]

    strategy:
      matrix:
        include:
          - name: linux-generic
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            exec_postfix: "linux-x86_64-v1"
            rustflags: "-Ctarget-feature=+crt-static"
            cflags: ""
            ext: ""

          - name: linux-v2
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            exec_postfix: "linux-x86_64-v2"
            rustflags: "-Ctarget-feature=+crt-static -Ctarget-cpu=x86-64-v2"
            cflags: ""
            ext: ""

          - name: linux-v3
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            exec_postfix: "linux-x86_64-v3"
            rustflags: "-Ctarget-feature=+crt-static -Ctarget-cpu=x86-64-v3"
            cflags: ""
            ext: ""

          - name: linux-v4
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            exec_postfix: "linux-x86_64-v4"
            rustflags: "-Ctarget-feature=+crt-static -Ctarget-cpu=x86-64-v4"
            cflags: ""
            ext: ""

          - name: linux-v5
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            exec_postfix: "linux-x86_64-v5"
            rustflags: "-Ctarget-feature=+crt-static -Ctarget-cpu=x86-64-v4 -C target-feature=+gfni,+avx512bw,+avx512vl,+avx512vbmi,+avx512vbmi2,+avx512vnni,+avx512bitalg"
            cflags: ""
            ext: ""

          - name: linux-aarch64
            os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-musl
            exec_postfix: "linux-aarch64"
            rustflags: "-Ctarget-feature=+crt-static"
            cflags: ""
            ext: ""

          - name: windows-generic
            os: windows-latest
            target: x86_64-pc-windows-msvc
            exec_postfix: "windows-x86_64-v1"
            rustflags: "-Ctarget-feature=+crt-static"
            cflags: "/std:c11 /experimental:c11atomics"
            ext: ".exe"

          - name: windows-v2
            os: windows-latest
            target: x86_64-pc-windows-msvc
            exec_postfix: "windows-x86_64-v2"
            rustflags: "-Ctarget-feature=+crt-static -Ctarget-cpu=x86-64-v2"
            cflags: "/std:c11 /experimental:c11atomics"
            ext: ".exe"

          - name: windows-v3
            os: windows-latest
            target: x86_64-pc-windows-msvc
            exec_postfix: "windows-x86_64-v3"
            rustflags: "-Ctarget-feature=+crt-static -Ctarget-cpu=x86-64-v3"
            cflags: "/std:c11 /experimental:c11atomics"
            ext: ".exe"

          - name: windows-v4
            os: windows-latest
            target: x86_64-pc-windows-msvc
            exec_postfix: "windows-x86_64-v4"
            rustflags: "-Ctarget-feature=+crt-static -Ctarget-cpu=x86-64-v4"
            cflags: "/std:c11 /experimental:c11atomics"
            ext: ".exe"

          - name: windows-v5
            os: windows-latest
            target: x86_64-pc-windows-msvc
            exec_postfix: "windows-x86_64-v5"
            rustflags: "-Ctarget-feature=+crt-static -Ctarget-cpu=x86-64-v4 -C target-feature=+gfni,+avx512bw,+avx512vl,+avx512vbmi,+avx512vbmi2,+avx512vnni,+avx512bitalg"
            cflags: "/std:c11 /experimental:c11atomics"
            ext: ".exe"

          - name: macos
            os: macos-latest
            target: aarch64-apple-darwin
            exec_postfix: "macos"
            rustflags: ""
            cflags: ""
            ext: ""

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v4

      - name: Install musl
        if: contains(matrix.target, 'musl')
        run: sudo apt-get install -y musl-tools

      - name: Build
        env:
          RUSTFLAGS: ${{ matrix.rustflags }}
          CFLAGS: ${{ matrix.cflags }}
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --release --package engine --target ${{ matrix.target }}
          mv target/${{ matrix.target }}/release/tcheran${{ matrix.ext }} tcheran-${{ needs.metadata.outputs.engine-version }}-${{ matrix.exec_postfix }}${{ matrix.ext }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tcheran-${{ matrix.exec_postfix }}
          path: tcheran-${{ needs.metadata.outputs.engine-version }}-${{ matrix.exec_postfix }}${{ matrix.ext }}

  release:
    needs: [metadata, build-release-binary]
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          pattern: tcheran-*
          path: bins
          merge-multiple: true

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          changelog_anchor=$(echo ${{ needs.metadata.outputs.engine-version }} | tr -d 'v.')
          chmod +x bins/*linux*
          chmod +x bins/*macos*
          gh release create --draft \
            --notes "https://github.com/jgilchrist/tcheran/blob/master/CHANGELOG.md#${changelog_anchor}"  \
            --title ${{ needs.metadata.outputs.engine-version }} \
            ${{ needs.metadata.outputs.engine-version }} \
            bins/*
